### ISSUE TITLE
Program logging to stdout

### ISSUE THREAD

**Issue by fledder** [aaOpenSource/aaLog#13]
So when I first tried getting it to log to stdout, the aaLog logs themselves were coming out at debug level. In aaLogReader.cs, line 38 and 56 have
```c#
log4net.Config.BasicConfigurator.Configure();
```
which apparently overrides the settings in log.config and sends debug-level messages out stdout. Is there a reason we need that line? I commented it out and the std out works as expected; I will set the log levels to debug and see if the actual logging still works.

**Comment by arobinsongit** [comment]
We should be able to fine tune the Log4Net configuration to stop sending debugs to the stdout.  I am definitely not a log4net master, more just got it doing what I needed to do.

**Comment by logic-danderson** [comment]
I ran into this, too, and agree that removing those two lines of code fixes it.

On a related note, I think this line should be removed from aaLogReader:

[assembly: log4net.Config.XmlConfigurator(ConfigFile = "log.config", Watch = true)]

In my opinion that belongs in the hosting executable, not the library. The way it stands now the library is hard coded to use log.config, and maybe that's not what the application developer prefers. I tested it and logging still works without these lines in aaLogReader as long as the hosting app is configured correctly.

So that also involves log4net. Is it appropriate to include that here or should there be a separate issue for it? Either way, I'd be happy to work on a pull request (or separate pull requests) for these changes.

**Comment by arobinsongit** [comment]
I agree that including that in the library was a pretty dumb move.   Maybe you could open a separate issue and issue a PR against that.

**Comment by logic-danderson** [comment]
Will do.

**Comment by arobinsongit** [comment]
David - your thoughts on closing this issue?  I'm not certain if you addressed this in a separate issue?

**Comment by logic-danderson** [comment]
Yeah, it was handled by issue #21.

**Comment by arobinsongit** [comment]
Ok thanks.  Closing issue since it was adressed with Issue #21
